// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confupdateproductupdate20171223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confupdateproductupdate20171223));
        
        string IMigrationMetadata.Id
        {
            get { return "201712230546536_conf-update-product-update-20171223"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
