// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confupdateproductdefaultImage1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confupdateproductdefaultImage1));
        
        string IMigrationMetadata.Id
        {
            get { return "201712172215408_conf-update-product-defaultImage-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
