// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confaddtariffcategory1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confaddtariffcategory1));
        
        string IMigrationMetadata.Id
        {
            get { return "201712312233160_conf-add-tariff-category-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
