// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confaddcartwishList20171224 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confaddcartwishList20171224));
        
        string IMigrationMetadata.Id
        {
            get { return "201712240047197_conf-add-cart-wishList-20171224"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
