// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confupdateproductCategory20171227 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confupdateproductCategory20171227));
        
        string IMigrationMetadata.Id
        {
            get { return "201712270047510_conf-update-productCategory-20171227"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
