// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class conforderupdate201801211 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conforderupdate201801211));
        
        string IMigrationMetadata.Id
        {
            get { return "201801211833469_conf-order-update-2018-01-21-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
