// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confupdateorder201801152 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confupdateorder201801152));
        
        string IMigrationMetadata.Id
        {
            get { return "201801150837192_conf-update-order-2018-01-15-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
