// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confcartitemupdate201801192 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confcartitemupdate201801192));
        
        string IMigrationMetadata.Id
        {
            get { return "201801200146447_conf-cart-item-update-2018-01-19-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
