// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confinvoiceuserid201801171 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confinvoiceuserid201801171));
        
        string IMigrationMetadata.Id
        {
            get { return "201801190923394_conf-invoice-userid-2018-01-17-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
