// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confinvoiceupdate201802021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confinvoiceupdate201802021));
        
        string IMigrationMetadata.Id
        {
            get { return "201802021405460_conf-invoice-update-2018-02-02-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
