// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confapplicationuserupdate201801191 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confapplicationuserupdate201801191));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191939598_conf-application-user-update-2018-01-19-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
