// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confinvoicelogadd201801261 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confinvoicelogadd201801261));
        
        string IMigrationMetadata.Id
        {
            get { return "201801261349073_conf-invoice-log-add-2018-01-26-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
