// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confreviewupdate201801262 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confreviewupdate201801262));
        
        string IMigrationMetadata.Id
        {
            get { return "201801261516126_conf-review-update-2018-01-26-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
