// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confproductcategoryupdate201802161 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confproductcategoryupdate201802161));
        
        string IMigrationMetadata.Id
        {
            get { return "201802161909530_conf-product-category-update-2018-02-16-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
