// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confinvoiceitem20180117 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confinvoiceitem20180117));
        
        string IMigrationMetadata.Id
        {
            get { return "201801172116246_conf-invoice-item-2018-01-17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
