// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class conffinancetransactionupdate201801241 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conffinancetransactionupdate201801241));
        
        string IMigrationMetadata.Id
        {
            get { return "201801241905235_conf-finance-transaction-update-2018-01-24-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
