// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class conforderuserupdate201802041 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conforderuserupdate201802041));
        
        string IMigrationMetadata.Id
        {
            get { return "201802041342125_conf-order-user-update-2018-02-04-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
