// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confupdateeronfile201801151 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confupdateeronfile201801151));
        
        string IMigrationMetadata.Id
        {
            get { return "201801150925218_conf-update-eronfile-2018-01-15-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
